dist: xenial
language: python
python:
  - "3.7"
services:
  - mysql
env:
  global:
    - DJANGO_SETTINGS_MODULE="enroller.settings"
    - PYTHONPATH="/home/travis/build/my_github_name/my_github_project"
    - PIP_USE_MIRRORS=true
    - BUILD_ON_TRAVIS=true
  matrix:
    - DJANGO=2.2.2 DB=mysql
cache: pip
install:
  - pip install -r requirements.txt
before_script:
  - mysql -e 'create database test;' -u root
  # - python manage.py migrate --noinput
script:
  - ./manage.py test --pattern="test_*.py" tests

